services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    logging:
      driver: 'none' # Optional: Stops bloated logs from filling your disk

volumes:
  pgdata:
    driver: local

